### ISSUE TITLE
Publication Milestone

### ISSUE THREAD

**Issue by mattephi** [based-robotics/jaxadi#4]
- [x] ~~Pytorch from HLO (optional module)~~ currently impossible
- [x] ~~Compare pytorch (cusadi), pytorch (our), jax, cuda, cpu, mjx~~ We compare cusadi(cuda) vs jaxadi directly. Comparison of pinocchio+casadi+jaxadi vs mjx is yet to come
- [ ] ~~Pytrees + comparison~~ (gave up the idea)
- [x] prettify readme
- [x] cool logo
- [x] separate examples and benchmarks
- [x] add test on examples
